'use client'
import { CalendarDays, ChefHat, Home, Moon, Search, ShoppingBasket, Sparkles, Sun, UtensilsCrossed, X } from 'lucide-react'
export type View = 'home' | 'surprise' | 'browse' | 'pantry' | 'planner' | 'meals' | 'shopping'
export function Sidebar({ active, onNavigate, dark, onToggleTheme, mobileOpen, onClose }: { active: View; onNavigate: (view: View) => void; dark: boolean; onToggleTheme: () => void; mobileOpen?: boolean; onClose?: () => void }) {
 const items = [['home','Home',Home],['browse','Explore',Search],['planner','Planner',CalendarDays],['shopping','Shopping',ShoppingBasket],['meals','My Meals',UtensilsCrossed]] as const
 return <><div className={`fixed inset-0 z-40 bg-foreground/20 lg:hidden ${mobileOpen ? 'block' : 'hidden'}`} onClick={onClose} aria-hidden="true" /><aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-border bg-card p-5 shadow-xl transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
  <div className="mb-8 flex items-start justify-between"><button className="flex items-center gap-3 text-left" onClick={() => { onNavigate('home'); onClose?.() }}><span className="flex size-11 items-center justify-center rounded-2xl bg-accent text-accent-foreground"><ChefHat className="size-5" /></span><span><strong className="block font-serif text-2xl leading-none text-accent">Chakula</strong><span className="mt-1 block text-xs text-muted-foreground">Modern Kenyan dining</span></span></button><button className="icon-button lg:hidden" onClick={onClose} aria-label="Close navigation"><X className="size-4" /></button></div>
  <div className="mb-6 rounded-2xl bg-secondary p-4"><p className="text-sm font-semibold">Welcome to Chakula</p><p className="mt-1 text-xs text-muted-foreground">Leo tunakula nini?</p></div>
  <nav className="flex flex-1 flex-col gap-2" aria-label="Main navigation">{items.map(([view,label,Icon]) => <button key={view} onClick={() => { onNavigate(view); onClose?.() }} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold transition hover:bg-secondary ${active === view ? 'bg-secondary text-foreground shadow-sm' : 'text-muted-foreground'}`} aria-current={active === view ? 'page' : undefined}><Icon className="size-5" />{label}</button>)}</nav>
  <div className="border-t border-border pt-4"><button onClick={onToggleTheme} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold text-muted-foreground hover:bg-secondary">{dark ? <Sun className="size-5" /> : <Moon className="size-5" />}{dark ? 'Light theme' : 'Dark theme'}</button><button onClick={() => onNavigate('surprise')} className="mt-2 flex w-full items-center gap-3 rounded-xl bg-accent px-4 py-3 text-left text-sm font-semibold text-accent-foreground hover:opacity-90"><Sparkles className="size-5" /> Surprise me</button></div>
 </aside></>
}
