'use client'

import { FormEvent, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { Eye, EyeOff } from 'lucide-react'

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); const { error } = await createClient().auth.signInWithPassword({ email, password }); setLoading(false); if (error) { setError(error.message.toLowerCase().includes('confirm') ? 'Please confirm your email before signing in.' : 'Invalid email or password.'); return } router.replace('/') ; router.refresh() }
  return <main className="flex min-h-screen items-center justify-center bg-background px-5"><form onSubmit={submit} className="panel w-full max-w-md"><p className="eyebrow text-accent">chakula</p><h1 className="mt-3 font-serif text-4xl">Welcome back.</h1><p className="mt-3 leading-6 text-muted-foreground">Sign in to keep your meals, pantry, planner, and preferences synced.</p><label className="field-label mt-8 block">Email<input className="text-input mt-2 w-full" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="field-label mt-4 block">Password<div className="relative mt-2"><input className="text-input w-full pr-12" type={showPassword ? 'text' : 'password'} required value={password} onChange={(e) => setPassword(e.target.value)} /><button type="button" className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></div></label>{error && <p className="mt-4 text-sm text-destructive" role="alert">{error}</p>}<button className="primary-button mt-6 w-full" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button><div className="mt-5 flex items-center justify-between text-sm"><Link className="font-semibold text-accent hover:underline" href="/forgot-password">Forgot password?</Link><Link className="font-semibold text-accent hover:underline" href="/signup">Create account</Link></div><p className="mt-5 text-xs leading-5 text-muted-foreground">Your account is secured by Supabase Auth. Credentials are never stored in the frontend.</p></form></main>
}
